### ISSUE TITLE
Event Alert Customization

### ISSUE THREAD

**Issue by guaj** [guaj/SemesterPlanner-Server#1]
As a user, I want to be able to customize my calendar alerts because it gives me more flexibility if an action is required.

The user will be able to customize calendar events and alerts extensively, allowing for multiple alerts over different time periods (eg. remind before day of event by 1 day and 1 week) and selection of specific day and time for alert.

Business Value: Medium
Priority: low
Effort: 5

**Comment by mnashat** [comment]
Feature has been cancelled. Refer to [based-kwl/SemesterPlanner-client#34](https://github.com/based-kwl/SemesterPlanner-client/issues/34).
