### ISSUE TITLE
Criteria-based User Search

### ISSUE THREAD

**Issue by guaj** [guaj/SemesterPlanner-Server#10]
As a user, I want to be able to find users based on specific criteria so I can study with them.
The user will be able to search for other users based on their preferred criteria. This allows them to find other users that are more suited to their study requirements. Minimum of 1 criteria for the search. (it’s a search bar)

Business Value: L
Priority: Medium
Effort: 5

**Comment by mnashat** [comment]
Feature has been cancelled. Refer to [based-kwl/SemesterPlanner-client#25](https://github.com/based-kwl/SemesterPlanner-client/issues/25).
