### ISSUE TITLE
Dictation-based Event Creation

### ISSUE THREAD

**Issue by guaj** [guaj/SemesterPlanner-Server#13]
As a user, I want to be able to add a calendar event using voice/dictation to save time in entering event information.

The user will be able to dictate information into each field when creating new events. **shouldn’t this be handled by the OS’s built-in dictation keyboard?

Business Value: small
Priority: low
Effort: 21

**Comment by mnashat** [comment]
Feature has been cancelled. Refer to [based-kwl/SemesterPlanner-client#22](https://github.com/based-kwl/SemesterPlanner-client/issues/22).
