### ISSUE TITLE
Camera-based Event Creation

### ISSUE THREAD

**Issue by guaj** [guaj/SemesterPlanner-Server#14]
As a user, I want to add a calendar event using camera/text recognition to save time in entering event information.

The user will be able to use their camera to take a picture of an event, and the app will be able to extract details of the event (such as time and date), and add them into the relevant event creation fields, giving the user the option of checking the details before creating the event.

Business Value: XL
Priority: High
Effort: 21

**Comment by mnashat** [comment]
Feature implemented. Refer to [based-kwl/SemesterPlanner-client#21](https://github.com/based-kwl/SemesterPlanner-client/issues/21).
