### ISSUE TITLE
Screenshot-based Class Scheduling

### ISSUE THREAD

**Issue by guaj** [guaj/SemesterPlanner-Server#15]
As a user, I want to add my Concordia class schedule from a photo so I can keep track of my classes.
The user will be able to upload a screenshot of their schedule to the app. The app will then pull the schedule information from the screenshot and add those events into their calendar automatically.

Business Value: XL
Priority: High
Effort: 21

**Comment by mnashat** [comment]
Feature was implemented. Refer to [based-kwl/SemesterPlanner-client#20](https://github.com/based-kwl/SemesterPlanner-client/issues/20) for more information.
