### ISSUE TITLE
Document Upload

### ISSUE THREAD

**Issue by guaj** [guaj/SemesterPlanner-Server#2]
As a user, I want to be able to upload documents so that I can share information with other users.

The user will be able to upload documents to their account publicly, allowing other users to view these documents.

Business Value: small
Priority: low
Effort: 5

**Comment by mnashat** [comment]
Feature has been cancelled. Refer to [based-kwl/SemesterPlanner-client#33](https://github.com/based-kwl/SemesterPlanner-client/issues/33).
