### ISSUE TITLE
Data validation - server 

### ISSUE THREAD

**Issue by guaj** [guaj/SemesterPlanner-Server#22]
Validate user profile information 
tasks
- [x] validate entered user registration information
- [x] validate modified user profile information

**Comment by mnashat** [comment]
@guaj Isn't this issue completed?

**Comment by mnashat** [comment]
Completed using validators at [SemesterPlanner-Server/src/validator/](https://github.com/guaj/SemesterPlanner-Server/tree/main/src/validator). These include:
- Event validator
- Friend validator
- Login validator
- Message validator
- Room validator
- Student Validator
