### ISSUE TITLE
UI prototype

### ISSUE THREAD

**Issue by guaj** [guaj/SemesterPlanner-Server#24]
- [ ] calendar prototype (calendar display, event creation, hyperlink for event, event creation + recurrent), event colour tagging)
- [x] sign in
- [x] registration
- [x] navigation menu
- [x] user profile modification + privacy toggle

sprint 3
- [ ] virtual study room
- [ ] search bar
- [ ] to confirm prototype with the group and Amanda

**Comment by mnashat** [comment]
Issue implemented and closed. Refer to [based-kwl/SemesterPlanner-client#10](https://github.com/based-kwl/SemesterPlanner-client/issues/10).
