### ISSUE TITLE
Study Timer

### ISSUE THREAD

**Issue by guaj** [guaj/SemesterPlanner-Server#3]
As a student, I want to have a display timer to accurately track my study times.

The user will be able to start a study timer when they start studying, allowing them to record a more accurate study time in the app and improving overall accuracy of provided statistics.

Business Value: Small
Priority: Low
Effort: 5

**Comment by mnashat** [comment]
Feature has been cancelled. Refer to [based-kwl/SemesterPlanner-client#32](https://github.com/based-kwl/SemesterPlanner-client/issues/32).
