### ISSUE TITLE
Study Notes Sharing

### ISSUE THREAD

**Issue by guaj** [guaj/SemesterPlanner-Server#4]
As a user, I want to be able to share study notes with others to help them with their studying.

The user will be able to share their study notes with other students that are on their friend list and have the same virtual study room access. This can help students that may have missed some lectures or are having difficulty grasping some of the concepts being discussed.
Business Value: M
Priority: low
Effort:8

**Comment by mnashat** [comment]
Feature has been implemented. Refer to [based-kwl/SemesterPlanner-client#31](https://github.com/based-kwl/SemesterPlanner-client/issues/31).
