### ISSUE TITLE
Course Study Hour Estimator

### ISSUE THREAD

**Issue by guaj** [guaj/SemesterPlanner-Server#6]
As a user, I want to know how many hours I need to study per class so that I can adjust my schedule accordingly.

The user will be provided with required study hours per course depending on credit hours per course. This will correspond to the suggested study hours estimated by Concordia’s paper-based study planner.

Business Value: XL
Priority: High
Effort: 2

**Comment by mnashat** [comment]
Feature has been implemented. Refer to [based-kwl/SemesterPlanner-client#29](https://github.com/based-kwl/SemesterPlanner-client/issues/29).
