### ISSUE TITLE
Study Plan Automatic Adaptation

### ISSUE THREAD

**Issue by guaj** [guaj/SemesterPlanner-Server#7]
As a user, I want my study times to adapt based on my needs in order to give all courses the study time required.

The user’s suggested study plan will be modified to adjust for missing or extra studied time, shifting focus towards less studied courses.

Business Value: L
Priority: Medium
Effort: 13

**Comment by mnashat** [comment]
Feature has been cancelled. Refer to [based-kwl/SemesterPlanner-client#28](https://github.com/based-kwl/SemesterPlanner-client/issues/28).
