### ISSUE TITLE
Study Statistics

### ISSUE THREAD

**Issue by guaj** [guaj/SemesterPlanner-Server#8]
As a user, I want to see my study time statistics to improve my efficiency.

The user will be able to views statistics of their study times and study time breakdowns for any given day, allowing them to plan for improvements in their study times (eg. Compensate missing study times on weekends, shift study focus from one course to another, etc.)

2.c The user will be able to see statistics of study time per course, allowing them to find courses with lower study times and adjust their studying priorities.

Daily, weekly, monthly

Business Value: XL
Priority: medium
Effort: 21

**Comment by mnashat** [comment]
Feature has been implemented. Refer to [based-kwl/SemesterPlanner-client#27](https://github.com/based-kwl/SemesterPlanner-client/issues/27).
