### ISSUE TITLE
Daily Study Recaps

### ISSUE THREAD

**Issue by guaj** [guaj/SemesterPlanner-Server#9]
As a user, I want to receive end-of-day study recaps to check if I am on track with my studies.

The user receives a daily study recap, detailing the study schedule intended for that day. The user then confirms the study times that were actually completed. This allows the user to keep track of the actual study time with respect to the planned study time.

Business Value: XL
Priority: High
Effort: 13

**Comment by mnashat** [comment]
Feature has been implemented. Refer to [based-kwl/SemesterPlanner-client#26](https://github.com/based-kwl/SemesterPlanner-client/issues/26).
